name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      enviroment:
        description: "배포 환경"
        required: true
        default: 'production'

jobs:
  build:
    env:
      name: seun
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Run script file
        run: source run.sh
      - name: log runner tools version
        run: |
          node -v
          java --version
          echo $name